import f_bookcase from './furniture/bookcase.png';
import f_cabinet from './furniture/cabinet.png';
import f_cooler from './furniture/cooler.png';
import f_counter from './furniture/counter.png';
import f_desk_files from './furniture/desk-files.png';
import f_desk_laptop from './furniture/desk-laptop.png';
import f_foosball from './furniture/foosball.png';
import f_plant from './furniture/plant.png';
import f_sofa from './furniture/sofa.png';
import f_stool from './furniture/stool.png';
import f_table_chess from './furniture/table-chess.png';
import f_table_low from './furniture/table-low.png';

import w_clock from './wall/clock.png';
import w_picture from './wall/picture.png';
import w_pinboard from './wall/pinboard.png';
import w_plant_hanging from './wall/plant-hanging.png';
import w_shelf from './wall/shelf.png';
import w_whiteboard from './wall/whiteboard.png';
import w_window from './wall/window.png';

/**
 * WHERE EVERY OBJECT IN THE ROOM COMES FROM, AND HOW BIG IT IS.
 * → docs/SPEC-office-art.md §3 · generated by scripts/gen-furniture
 *
 * ┌──────────────────────────────────────────────────────────────────────────┐
 * │ ⚠ THE SHEET GIVES SHAPE. IT DOES NOT GIVE SCALE.                        │
 * │                                                                          │
 * │ The generator draws every object to fill its own cell, so the pixel       │
 * │ heights coming out of one sheet are NOT in proportion to each other. On   │
 * │ the floor sheet they happened to be: anchoring ookcase at a person's   │
 * │ height put stool at 34% of one — the same number the spec had written   │
 * │ down BEFORE anything was generated, which is what makes that anchor       │
 * │ trustworthy rather than lucky.                                           │
 * │                                                                          │
 * │ The wall sheet is the opposite: clock measured 67% of a person's        │
 * │ height. A real wall clock is about 18%. Every h under WALL is         │
 * │ therefore a DESIGN DECISION, not a measurement, and changing one is a     │
 * │ decision about the room rather than a correction of a number.             │
 * └──────────────────────────────────────────────────────────────────────────┘
 *
 * h is height in WORLD units, where a person is CH_H = 177.
 * r is width ÷ height of the source file, so callers derive width from h
 * and a piece can never be stretched by a caller doing its own arithmetic.
 */
export interface Piece {
  /** The file, imported as a URL. */
  src: string;
  /** Height in world units. A person is CH_H = 177. */
  h: number;
  /** width / height of the source image. */
  ar: number;
}

/** Objects that stand on the FLOOR. Anchor: bottom-centre, on the floor line. */
export const FURNITURE = {
  'bookcase': { src: f_bookcase, h: 177, ar: 0.4984 },
  'cabinet': { src: f_cabinet, h: 119, ar: 0.5302 },
  'cooler': { src: f_cooler, h: 133, ar: 0.2926 },
  'counter': { src: f_counter, h: 120, ar: 0.8018 },
  'desk-files': { src: f_desk_files, h: 105, ar: 2.7819 },
  'desk-laptop': { src: f_desk_laptop, h: 116, ar: 1.3889 },
  'foosball': { src: f_foosball, h: 101, ar: 1.1522 },
  'plant': { src: f_plant, h: 146, ar: 0.5038 },
  'sofa': { src: f_sofa, h: 97, ar: 1.5284 },
  'stool': { src: f_stool, h: 60, ar: 0.8611 },
  'table-chess': { src: f_table_chess, h: 94, ar: 0.9 },
  'table-low': { src: f_table_low, h: 70, ar: 1.189 },
} as const satisfies Record<string, Piece>;

/** Objects that hang on the WALL. Anchor: centre, at a height the room chooses. */
export const WALL = {
  'clock': { src: w_clock, h: 35, ar: 1 },
  'picture': { src: w_picture, h: 45, ar: 0.8016 },
  'pinboard': { src: w_pinboard, h: 75, ar: 1.3051 },
  'plant-hanging': { src: w_plant_hanging, h: 93, ar: 0.3981 },
  'shelf': { src: w_shelf, h: 40, ar: 1.5314 },
  'whiteboard': { src: w_whiteboard, h: 117, ar: 1.4978 },
  'window': { src: w_window, h: 160, ar: 0.9433 },
} as const satisfies Record<string, Piece>;

export type FurnitureId = keyof typeof FURNITURE;
export type WallId = keyof typeof WALL;

/** Width in world units, derived — never stored, so it cannot drift from r. */
export function widthOf(p: Piece): number {
  return p.h * p.ar;
}