/**
 * The release signing keys — PUBLIC halves only. → docs/SPEC-packaging.md §3.6
 *
 * Generated by `scripts/release-keys.ts` on 2026-09-14. The private halves never
 * enter any repository: `working` sits on the maintainer's machine and signs
 * every `stable.json`; `backup` is kept offline and exists for the day
 * `working` is lost. The app accepts a manifest signed by either.
 *
 * 🔴 NEVER EDIT OR REPLACE THESE BY HAND. Every installed copy verifies the
 * update manifest against exactly these values, and a copy built before a
 * change keeps the old ones for as long as it stays installed.
 */
export const RELEASE_PUBLIC_KEYS: readonly { readonly name: 'working' | 'backup'; readonly spki: string }[] = [
  { name: 'working', spki: 'MCowBQYDK2VwAyEAXCwi98H2u0UFN83B0/ekj4jjjOFTd18DSGHwceC9fak=' },
  { name: 'backup', spki: 'MCowBQYDK2VwAyEAkv+22aGfsVKeQ/WpMMGrfERd2y1Br2/F9VlGV3JxWK0=' },
];
