/**
 * Create the two release signing keys. → docs/SPEC-packaging.md §3.6
 *
 * 🔴 RUN ONCE, ON THE MAINTAINER'S MACHINE. The private halves are written
 * outside every repository and never printed; the public halves go into
 * `src/core/release-keys.ts`, which is committed and compiled into every build.
 *
 * ⚠ IT REFUSES TO OVERWRITE ANYTHING. Replacing a key that has shipped silences
 * the update channel for every copy that carries the old public key — so a
 * second run is a mistake to stop, not a convenience to offer.
 *
 * Two keys, both accepted by the app (settled 15/09/2026): `working` stays on
 * this machine and signs every `stable.json`; `backup` is moved offline — paper
 * or a password manager — and deleted from this disk. It exists for the day
 * `working` is lost.
 *
 * Run: node --experimental-strip-types scripts/release-keys.ts [--dir <folder>]
 */

import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT_FILE = path.join(ROOT, 'src', 'core', 'release-keys.ts');

const dirAt = process.argv.indexOf('--dir');
const DIR =
  dirAt > 0 && process.argv[dirAt + 1]
    ? path.resolve(process.argv[dirAt + 1]!)
    : path.join(os.homedir(), '.agentco-release');

function refuse(message: string): never {
  console.error(`\n✗ ${message}\n`);
  process.exit(2);
}

if (fs.existsSync(OUT_FILE)) {
  refuse(`${path.relative(ROOT, OUT_FILE)} already exists — the keys were made. Refusing to replace them.`);
}
for (const name of ['working', 'backup']) {
  const file = path.join(DIR, `${name}.key`);
  if (fs.existsSync(file)) refuse(`${file} already exists. Refusing to overwrite a private key.`);
}

fs.mkdirSync(DIR, { recursive: true, mode: 0o700 });

const made = (['working', 'backup'] as const).map((name) => {
  const { publicKey, privateKey } = crypto.generateKeyPairSync('ed25519');

  // Prove the pair signs and verifies before anything is written anywhere.
  const probe = crypto.randomBytes(32);
  if (!crypto.verify(null, probe, publicKey, crypto.sign(null, probe, privateKey))) {
    refuse(`the generated ${name} key pair does not verify its own signature`);
  }

  const file = path.join(DIR, `${name}.key`);
  // `wx`: fail rather than replace, even if the check above raced something.
  fs.writeFileSync(file, privateKey.export({ type: 'pkcs8', format: 'pem' }), { mode: 0o600, flag: 'wx' });
  const spki = (publicKey.export({ type: 'spki', format: 'der' }) as Buffer).toString('base64');
  return { name, file, spki };
});

const today = new Date().toISOString().slice(0, 10);
const source = `/**
 * The release signing keys — PUBLIC halves only. → docs/SPEC-packaging.md §3.6
 *
 * Generated by \`scripts/release-keys.ts\` on ${today}. The private halves never
 * enter any repository: \`working\` sits on the maintainer's machine and signs
 * every \`stable.json\`; \`backup\` is kept offline and exists for the day
 * \`working\` is lost. The app accepts a manifest signed by either.
 *
 * 🔴 NEVER EDIT OR REPLACE THESE BY HAND. Every installed copy verifies the
 * update manifest against exactly these values, and a copy built before a
 * change keeps the old ones for as long as it stays installed.
 */
export const RELEASE_PUBLIC_KEYS: readonly { readonly name: 'working' | 'backup'; readonly spki: string }[] = [
${made.map((k) => `  { name: '${k.name}', spki: '${k.spki}' },`).join('\n')}
];
`;
fs.writeFileSync(OUT_FILE, source, { encoding: 'utf8', flag: 'wx' });

console.log('\nRelease keys created.\n');
for (const k of made) console.log(`  ${k.name.padEnd(8)} private key → ${k.file}`);
console.log(`  public keys          → ${path.relative(ROOT, OUT_FILE)} (commit this file)\n`);
console.log('Next:');
console.log(`  1. Copy ${made[1]!.file} somewhere OFFLINE (password manager, or print it), then delete it from this disk.`);
console.log(`  2. Keep ${made[0]!.file} here — scripts/release-web.ts signs with it. Back it up too.`);
